trigger: none

variables:
  # This variable group must exist & populated with acr-password
  - group: shared-secrets

  - name: app-name
    value: 'vuego-demoapp'
  - name: res-group
    value: 'Demo.AppService'
  - name: azure-connection
    value: 'Azure (AIRS)'
  - name: acr-name
    value: 'bcdemo'
  - name: appservice-plan
    value: 'SharedAppPlanLinux'
  - name: location
    value: 'North Europe'

stages:
#
# Test
#
- stage: deployTest
  displayName: 'Test'

  variables:
    appservice-name: '$(app-name)-test'

  jobs:
  - template: templates/arm-app-service.yml
    parameters:
      envName: Test

#
# Staging
#
- stage: deployStaging
  displayName: 'Staging'

  variables:
    appservice-name: '$(app-name)-staging'

  jobs:
  - template: templates/arm-app-service.yml
    parameters:
      envName: Staging

#
# Prod
#
- stage: deployProd
  displayName: 'Prod'

  variables:
    appservice-name: '$(app-name)'

  jobs:
  - template: templates/arm-app-service.yml
    parameters:
      envName: Prod   

  - job: configureProdApp
    dependsOn: deployToAppService
    displayName: 'Configure Prod App Settings'
    pool:
      vmImage: Ubuntu-16.04
    variables:
      - group: vuego-demoapp-vars
    steps:
      - task: AzureCLI@1
        displayName: 'Set webapp config'
        inputs:
          azureSubscription: 'Azure (AIRS)'
          scriptLocation: inlineScript
          inlineScript: |
            az webapp config appsettings set -g $(res-group) -n $(appservice-name) --settings \
            RELEASE=$(Build.BuildNumber) \
            WEATHER_API_KEY=$(weather-key) \
            IPSTACK_API_KEY=$(ipstack-key)

  # - job: removeNonProd
  #   displayName: 'Remove Non Prod Apps'
  #   pool:
  #     vmImage: Ubuntu-16.04
  #   steps:
  #     - task: AzureCLI@1
  #       displayName: 'Remove Web Apps'
  #       inputs:
  #         azureSubscription: 'Azure (AIRS)'
  #         scriptLocation: inlineScript
  #         inlineScript: |
  #           az webapp delete -n $(app-name)-staging -g $(res-group)
  #           az webapp delete -n $(app-name)-test -g $(res-group) 